# Generated by Django 4.0.6 on 2022-07-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('액션', '액션'), ('로맨스', '로맨스'), ('공포', '공포'), ('범죄', '범죄'), ('스릴러', '스릴러'), ('SF', 'SF'), ('코미디', '코미디')], max_length=100, verbose_name='장르'),
        ),
    ]
