# Generated by Django 4.0.6 on 2022-07-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('horror', '공포'), ('SF', 'SF'), ('action', '액션'), ('romance', '로맨스'), ('comedy', '코미디'), ('thriller', '스릴러'), ('crime', '범죄')], max_length=100, verbose_name='장르'),
        ),
    ]
