# Generated by Django 4.0.6 on 2022-07-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('kind', models.CharField(max_length=50, verbose_name='종류')),
                ('content', models.TextField(verbose_name='설명')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('photo', models.ImageField(blank=True, upload_to='posts/%Y%m%d', verbose_name='사진')),
                ('content', models.TextField(verbose_name='내용')),
                ('interest', models.IntegerField(default=0, verbose_name='관심도')),
                ('devTools', models.CharField(choices=[('default', '----------'), ('DJANGO', 'django'), ('REACT', 'react'), ('SPRING', 'Spring'), ('NODEJS', 'Node.js'), ('JAVA', 'Java'), ('CPP', 'C++')], default='default', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tool', to='posts.devtool')),
            ],
        ),
    ]
