# Generated by Django 4.0.6 on 2022-07-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('kind', models.CharField(max_length=50, verbose_name='종류')),
                ('content', models.TextField(verbose_name='설명')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='interest',
            field=models.IntegerField(default=0, verbose_name='관심도'),
        ),
    ]
