# Generated by Django 4.0.6 on 2022-07-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='devTools',
            field=models.CharField(choices=[('REACT', 'react'), ('DJANGO', 'django'), ('CPP', 'C++'), ('JAVA', 'Java'), ('default', '----------'), ('NODEJS', 'Node.js'), ('SPRING', 'Spring')], max_length=20),
        ),
    ]
