# Generated by Django 4.0.6 on 2022-07-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_devtools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='devTools',
            field=models.CharField(choices=[('2', 'django'), ('1', '----------'), ('4', 'Spring'), ('5', 'Node.js'), ('7', 'C++'), ('6', 'Java'), ('3', 'react')], max_length=20),
        ),
    ]
