# Generated by Django 4.0.6 on 2022-07-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_devtools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='devTools',
            field=models.CharField(choices=[(5, 'Node.js'), (2, 'django'), (1, '----------'), (6, 'Java'), (7, 'C++'), (3, 'react'), (4, 'Spring')], max_length=20),
        ),
    ]
