# Generated by Django 4.0.6 on 2022-07-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_devtools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='devTools',
            field=models.CharField(choices=[(6, 'Java'), (2, 'django'), (4, 'Spring'), (1, '----------'), (3, 'react'), (5, 'Node.js'), (7, 'C++')], max_length=20),
        ),
    ]
