# Generated by Django 4.0.6 on 2022-07-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_devtools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='devTools',
            field=models.CharField(choices=[('SPRING', 'Spring'), ('DJANGO', 'django'), ('JAVA', 'Java'), ('NODEJS', 'Node.js'), ('default', '----------'), ('CPP', 'C++'), ('REACT', 'react')], default='default', max_length=20),
        ),
    ]
