# Generated by Django 4.0.6 on 2022-07-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_devtools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='devTools',
            field=models.CharField(choices=[('default', '----------'), ('DJANGO', 'django'), ('REACT', 'react'), ('SPRING', 'Spring'), ('NODEJS', 'Node.js'), ('JAVA', 'Java'), ('CPP', 'C++')], default='default', max_length=20),
        ),
    ]
