# Generated by Django 4.0.6 on 2022-07-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_devtools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='devTools',
            field=models.CharField(choices=[('default', '----------'), ('django', 'django'), ('react', 'react'), ('Spring', 'Spring'), ('Node.js', 'Node.js'), ('Java', 'Java'), ('C++', 'C++')], default='default', max_length=20),
        ),
    ]
